server:
  port: 30001

spring:
  application:
    name: account
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url : jdbc:mysql://myhost:3306/db_account_1?useUnicode=true&characterEncoding=utf8
    username: test
    password: test
    type: com.alibaba.druid.pool.DruidDataSource

rocketmq:
  name-server: myhost:9876
  producer:
    group: tx_producer
    send-message-timeout: 6000